Fixed Github workflows, actions. And fixed docker building and other repo actions. Streamlined tagging process
Signed-off-by: Lalith Kota <kotalalith@gmail.com>

diff --git a/.github/workflows/tag.yml b/.github/workflows/tag.yml
--- a/.github/workflows/tag.yml
+++ b/.github/workflows/tag.yml
@@ -11,11 +11,147 @@ on:
         required: true
         type: string
         default: latest
+      push-to-docker:
+        description: Build and Push Dockers
+        type: boolean
+        default: true
+      push-to-pypi:
+        description: Push modules to PyPI
+        type: boolean
+        default: true
+      push-to-stoplight:
+        description: Push API Docs to Stoplight
+        type: boolean
+        default: true
 jobs:
   tag-repo:
-    uses: openg2p/openg2p-packaging/.github/workflows/tag.yml@main
-    with:
-      new-tag: ${{ inputs.new-tag }}
-      previous-tag: ${{ inputs.previous-tag }}
-    secrets:
-      OPENG2P_BOT_GITHUB_PAT: ${{ secrets.OPENG2P_BOT_GITHUB_PAT }}
+    name: Tag Repo
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          fetch-tags: true
+      - name: Check tag convention
+        run: |
+          pattern="^v[0-9]+.[0-9]+.[0-9]+$"
+          if ! [[ ${{ inputs.new-tag }} =~ $pattern ]]; then
+            echo "Tag convention not followed"
+            exit 1
+          fi
+      - name: Check if the branch has moved at all
+        run: |
+          check_branch_and_exit (){
+            if [[ -z $(git diff $1) ]]; then
+              echo "::error::No changes on this branch. Tag not created"
+              exit 1
+            fi
+          }
+          if [[ "${{ inputs.previous-tag }}" == "latest" ]]; then
+            latest_tag=$(git describe --tags)
+            check_branch_and_exit "$latest_tag"
+          elif [[ "${{ inputs.previous-tag }}" != "None" ]]; then
+            check_branch_and_exit "${{ inputs.previous-tag }}"
+          fi
+
+      - name: Setup python
+        uses: actions/setup-python@v4
+        with:
+          python-version: "3.10"
+
+      - name: Changing version
+        run: |
+          for init_file in $(grep -rl "__version__ ="); do
+            if [[ $init_file =~ *.py ]]; then
+              version_line=$(grep "__version__" $init_file)
+              sed -i "s/$version_line/__version__ = \"${{ inputs.new-tag }}\"/g" $init_file
+            fi
+          done
+      - name: Removing github development package dependencies
+        run: |
+          for cleanup_file in $(grep -rl "to_be_removed_on_tag" Dockerfile.*); do
+            sed -i "/to_be_removed_on_tag/d" $cleanup_file
+          done
+
+      - name: Generate openapi json
+        if: ${{ inputs.push-to-stoplight }}
+        uses: ./.github/actions/openapi-generate.yml
+
+      - name: Commit Changes
+        uses: EndBug/add-and-commit@v7
+        with:
+          default_author: github_actions
+          message: "Preparing new tag ${{ github.event.inputs.git-ref }}"
+          add: "**/*.py Dockerfile.* api-docs"
+          push: false
+          tag: ${{ inputs.new-tag }}
+
+      - name: Push module to PyPI - openg2p-g2p-bridge-models
+        if: ${{ inputs.push-to-pypi }}
+        uses: ./.github/actions/pypi-publish.yml
+        with:
+          MODULE_PATH: openg2p-g2p-bridge-models
+          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
+      - name: Push module to PyPI - openg2p-g2p-bridge-api
+        if: ${{ inputs.push-to-pypi }}
+        uses: ./.github/actions/pypi-publish.yml
+        with:
+          MODULE_PATH: openg2p-g2p-bridge-api
+          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
+      - name: Push module to PyPI - openg2p-g2p-bridge-bank-connectors
+        if: ${{ inputs.push-to-pypi }}
+        uses: ./.github/actions/pypi-publish.yml
+        with:
+          MODULE_PATH: openg2p-g2p-bridge-bank-connectors
+          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
+      - name: Push module to PyPI - openg2p-g2p-bridge-celery-beat-producers
+        if: ${{ inputs.push-to-pypi }}
+        uses: ./.github/actions/pypi-publish.yml
+        with:
+          MODULE_PATH: openg2p-g2p-bridge-celery-beat-producers
+          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
+      - name: Push module to PyPI - openg2p-g2p-bridge-celery-workers
+        if: ${{ inputs.push-to-pypi }}
+        uses: ./.github/actions/pypi-publish.yml
+        with:
+          MODULE_PATH: openg2p-g2p-bridge-celery-workers
+          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
+
+      - name: Push OpenAPI to Stoplight
+        if: ${{ inputs.push-to-stoplight }}
+        uses: ./.github/actions/openapi-publish.yml
+        with:
+          STOPLIGHT_PROJECT_TOKEN: ${{ secrets.STOPLIGHT_PROJECT_TOKEN }}
+
+      - name: Build and Push Docker for API
+        uses: ./.github/actions/docker-build.yml
+        if: ${{ inputs.push-to-docker }}
+        with:
+          NAMESPACE: ${{ secrets.docker_hub_organisation || 'openg2p' }}
+          SERVICE_NAME: openg2p-g2p-bridge-api
+          DOCKERFILE_PATH: Dockerfile.api
+          DOCKER_HUB_TOKEN: ${{ secrets.docker_hub_token }}
+          DOCKER_HUB_ACTOR: ${{ secrets.docker_hub_actor }}
+          TAG: ${{ inputs.new-tag }}
+      - name: Build and Push Docker for Celery Producers
+        uses: ./.github/actions/docker-build.yml
+        if: ${{ inputs.push-to-docker }}
+        with:
+          NAMESPACE: ${{ secrets.docker_hub_organisation || 'openg2p' }}
+          SERVICE_NAME: openg2p-g2p-bridge-celery-beat-producers
+          DOCKERFILE_PATH: Dockerfile.producers
+          DOCKER_HUB_TOKEN: ${{ secrets.docker_hub_token }}
+          DOCKER_HUB_ACTOR: ${{ secrets.docker_hub_actor }}
+          TAG: ${{ inputs.new-tag }}
+      - name: Build and Push Docker for Celery Workers
+        uses: ./.github/actions/docker-build.yml
+        if: ${{ inputs.push-to-docker }}
+        with:
+          NAMESPACE: ${{ secrets.docker_hub_organisation || 'openg2p' }}
+          SERVICE_NAME: openg2p-g2p-bridge-celery-workers
+          DOCKERFILE_PATH: Dockerfile.workers
+          DOCKER_HUB_TOKEN: ${{ secrets.docker_hub_token }}
+          DOCKER_HUB_ACTOR: ${{ secrets.docker_hub_actor }}
+          TAG: ${{ inputs.new-tag }}
